### ISSUE TITLE
switch testing to BaseTestNext

### ISSUE THREAD

**Issue by tbreloff** [Evizero/LearnBase.jl#11]
This will be a pain in the ***, but I think worthwhile.  The major problem with the current testing is that, on an error, the tests are halted, and so you can't see the results of all the tests.  The output is also a little nicer, and things like your `msg`/`msg2` can be handled nicely by creating nested contexts.

I'll take this on, if you approve of the switch.

**Comment by Evizero** [comment]
I looked at factcheck a while back and decided not to use it until now, simply because I thought the standard stuff enough. Recently I have been playing with the idea but it is my understanding that the testing changes a lot with 0.5, so I decided to wait it out. Now that I think about it I can't remember where I got this information from. I might be wrong there

Anyhow, I have no strong feelings either way. If your prefer it then I'm completely ok with that

**Comment by Evizero** [comment]
I am using FactChecks.jl for a package that I am working on and it is quite interesting.

I found this is a nice way to organize tests:

```julia
using FactCheck
  
tests = [
    ("tst_common.jl", "Utility methods"),
    ("tst_blabla.jl", "The important blabla functionality"),
]
  
for (fn, desc) in tests
    facts("$desc ($fn)") do
        include(fn)
    end
end
  
FactCheck.exitstatus()         
``

**Comment by Evizero** [comment]
how about https://github.com/JuliaCI/BaseTestNext.jl ?

**Comment by tbreloff** [comment]
Worth a try! I don't know enough about it to say if it's better/worse.
